config/routes.rb
Rails.application.routes.draw do

  get 'ticket_logs' => "ticket_logs#index", as: :ticket_logs#チケット使用履歴
  delete "ticket_logs", to: "ticket_logs#destroy", as: 'logs_destroy'
  get 'ticket' => "tickets#user_have_ticket", as: :user_have_ticket#チケット使用履歴

  root 'static_pages#top'#トップページ
  get 'paypaytest' => "static_pages#paypaytest"#paypaytest
  get 'top_owner' => "static_pages#top_owner"#経営者様トップページ
  get 'top_user' => "static_pages#top_user"#利用者様トップページ
  get 'megurume_line' => "static_pages#megurume_line"#LINE誘導
  get 'discussion' => "static_pages#discussion"#相談窓口
  get 'specified_commercial_transaction_law' => "static_pages#specified_commercial_transaction_law"#特定商取引法
  get 'how_to_use' => "subscriptions#how_to_use", as: :how_to_use#ご利用方法について
  get 'plan_description' => "subscriptions#plan_description", as: :plan_description#プラン説明
  get 'kiyaku' => "subscriptions#kiyaku", as: :kiyaku#利用規約
  get 'privacy_policy' => "subscriptions#privacy_policy", as: :privacy_policy#プライバシーポリシー
  get 'site' => "subscriptions#site", as: :site#サイトについて
  get 'company_profile' => "subscriptions#company_profile", as: :company_profile#会社概要

  get 'subscriptions/setup', to: 'subscriptions#setup', as: :setup_subscriptions#経営者のプラン内容
  get '/cancel', to: 'user_plans#cancel'
  get '/success', to: 'user_plans#success'
  get '/private_store_cancel', to: 'private_store_user_plans#cancel'
  get '/private_store_success', to: 'private_store_user_plans#success'

  get 'categories/shop_list', to: 'categories#shop_list', as: :shop_list_categories
  get 'categories/recommend', to: 'categories#recommend', as: :recommend_categories#おすすめショップ

  get 'subscriptions/show_sample', to: 'subscriptions#show_sample', as: :show_sample_subscriptions
  get 'subscriptions/shop_case', to: 'subscriptions#shop_case', as: :shop_case#ショップ事例

  get 'subscriptions/:id/ticket', to: 'users#ticket', as: :use_ticket #チケット発行ページ
  get 'private_store/:id/ticket', to: 'private_store_users#ticket', as: :private_store_use_ticket #private_store用チケット発行ページ
  get 'private_store/:id/new_ticket', to: 'private_store_user_plans#new', as: :private_store_new_ticket #private_store用サブスクを始める
  get 'subscription/:id/new_ticket', to: 'user_plans#new', as: :subscription_new_ticket #subscription用サブスクを始める

  get '/subscriptions/:subscription_id/subscription_reviews', to: 'reviews#subscription_reviews', as: :subscription_reviews #サブスクレビューページ
  get '/private_stores/:private_store_id/private_store_reviews', to: 'reviews#private_store_reviews', as: :private_store_reviews #個人店舗レビューページ
  get '/subscriptions/:subscription_id/edit_subscription_reviews/:id', to: 'reviews#edit_subscription_reviews', as: :edit_subscription_reviews #サブスクレビューページ

  get '/ticket_success', to: 'tickets#ticket_success', as: :ticket_success
  patch 'users/:user_id/tickets/:id/ticket_update_after_second_time', to: 'tickets#ticket_update_after_second_time', as: :ticket_update_after_second_time
  patch 'users/:user_id/tickets/:id/edit_user_ticket', to: 'tickets#edit_user_ticket', as: :edit_user_ticket

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, path: 'users', controllers: {
   # omniauth_callbacks:  'users/omniauth_callbacks',
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/sign_up/confirm', to: 'users/registrations#confirm'
    patch 'users/sign_up/complete', to: 'users/registrations#complete'
    post 'users/sign_up/complete', to: 'users/registrations#complete'
    get "/devise/auth/facebook/callback" => "users/omniauth_callbacks#facebook"
    get "/devise/auth/twitter/callback" => "users/omniauth_callbacks#twitter"
    match "/users/auth/line" => "users/omniauth_callbacks#passthru", via: [:get, :post]
    match "/users/auth/line/callback" => "users/omniauth_callbacks#line", via: [:get, :post]
    get 'users/sign_up', to: 'users#new'
  end

  devise_for :owners, path: 'owners', controllers: {
    sessions:      'owners/sessions',
    passwords:     'owners/passwords',
    registrations: 'owners/registrations'
  }
  devise_scope :owner do
    get "/devise/auth/facebook_owner/callback" => "owners/omniauth_callbacks#facebook_owner"
    get "/devise/auth/twitter_owner/callback" => "owners/omniauth_callbacks#twitter_owner"
    match "/owners/auth/line" => "owners/omniauth_callbacks#passthru", via: [:get, :post]
    match "/owners/auth/line/callback" => "owners/omniauth_callbacks#line_owner", via: [:get, :post]
  end

  devise_scope :owner do
    post 'owners/sign_up/confirm', to: 'owners/registrations#confirm'
    patch 'owners/sign_up/complete', to: 'owners/registrations#complete'
    post 'owners/sign_up/complete', to: 'owners/registrations#complete'
  end

  resource :admin, except: %i(new create destroy) do
    get 'account', on: :collection #アカウントページ
    member do
      get 'private_owner_edit'
      patch 'private_owner_update'
      get 'subscription_owner_edit'
      patch 'subscription_owner_update'
      # patch 'private_stores/:private_stores_id/private_owner_update', to: 'admins#private_owner_update', as: :private_owner_update
      get 'owner_edit' #個人情報編集
      patch 'owner_update' #個人情報編集
      get 'user_edit' #
      patch 'user_update' #
    end
  end
  resources :blogs#管理者が書くサブスクnews
  get 'reviews/list' => "reviews#list"#利用者ではない人用の表示ページ
  get 'subscriptions/list' => "subscriptions#list"#まだ決まってない。使わないかもしれない
  get 'blogs/index'#まだ決まってない。使わないかもしれない

  get 'suports', to: "suports#index"#サポート画面
  post 'suports/confirm' => "suports#confirm"#サポート確認画面
  post 'suports/thanks' => "suports#thanks"#サポート完了通知仮面

  get 'contacts', to: "contacts#index"#お問い合わせ画面
  post 'contacts/confirm' => "contacts#confirm"#お問い合わせ確認画面
  post 'contacts/thanks' => "contacts#thanks"#お問い合わせ完了通知仮面

  resources :medias#メディア
  resources :interviews#経営者様インタビュー
  resources :cupons#クーポン
  resources :products#QRコード

  get 'owners/deleted_owners'#論理削除された経営者
  resources :owners do
    get :search, on: :collection #オーナーの名前であいまい検索 追加分
    get :subscription_private_store_select, on: :member #加盟店か個人店かの選択
    get :subscription_private_store_judging_select, on: :member #加盟店か個人店かの選択と審査の選択
    member do
      post "thanks" #会員登録完了通知画面
      get 'owner_account' #アカウントページ
      patch 'update_deleted_owners' #アカウントページ論理削除
    end
    resources :subscriptions do
      get 'like_lunch', on: :member
      member do
        get 'edit_recommend' #おすすめ追加よう
        patch 'update_recommend' #おすすめ店舗に加えるたり外すよう
        get '/owner_subscriptions', to: "subscriptions#owner_subscriptions", as: :owner_subscriptions
        post :takeout
      end
    end
    resources :private_stores do
      resources :images
      member do
        get 'edit_recommend' #おすすめ追加よう
        patch 'update_recommend' #おすすめ店舗に加えるたり外すよう
        #get "confirm", to: "private_store_user_plans#confirm"
        #get "update_confirm", to: "private_store_user_plans#update_confirm"
        #get 'plans_new', to: "private_store_user_plans#new", as: 'plans_new' #利用者のプラン内容
        #get "plans_edit", to: "private_store_user_plans#edit", as: 'plans_edit'
              #patch "plans_update", to: "private_store_user_plans#update", as: 'plans_update'
        #delete "plans_destroy", to: "private_store_user_plans#destroy", as: 'plans_destroy'
        get '/owner_private_stores', to: "private_stores#owner_private_stores", as: :owner_private_stores
        post :takeout
      end
    end
  end
  resources :maps
  resources :categories, only: %i(index) do
    get 'like_lunch', on: :member
    post 'search', on: :collection
  end
  get 'categories/trial_shop', to: 'categories#trial_shop', as: :trial_shop#トライアルのお店一覧
  get 'private_stores/private_all_shop', to: 'private_stores#private_all_shop', as: :private_all_shop#個人店舗のお店一覧
  get 'subscriptions/subscription_all_shop', to: 'subscriptions#subscription_all_shop', as: :subscription_all_shop#加盟店舗のお店一覧
  post 'subscriptions/subscription_confirm', to: 'subscriptions#subscription_confirm', as: :subscription_confirm#加盟店舗の審査の確認画面
  patch 'subscriptions/subscription_judging', to: 'subscriptions#subscription_judging'#加盟店舗の審査
  post 'subscriptions/subscription_judging', to: 'subscriptions#subscription_judging'#加盟店舗の審査

  post 'private_stores/private_store_confirm', to: 'private_stores#private_store_confirm', as: :private_store_confirm#個人店舗の審査の確認画面
  patch 'private_stores/private_store_judging', to: 'private_stores#private_store_judging'#個人店舗の審査
  post 'private_stores/private_store_judging', to: 'private_stores#private_store_judging'#個人店舗の審査

  get 'users/user_subscription_email', to: 'users#user_subscription_email' #加盟店の利用者から経営者へメール
  patch 'users/user_subscription_confirm', to: 'users#user_subscription_confirm'
  patch 'users/user_subscription_thanks', to: 'users#user_subscription_thanks'
  post 'users/user_subscription_thanks', to: 'users#user_subscription_thanks'

  get 'users/user_private_store_email', to: 'users#user_private_store_email' #加盟店の利用者から経営者へメール
  patch 'users/user_private_store_confirm', to: 'users#user_private_store_confirm'
  patch 'users/user_private_store_thanks', to: 'users#user_private_store_thanks'
  post 'users/user_private_store_thanks', to: 'users#user_private_store_thanks'

  get 'users/deleted_users'##論理削除された利用者
  resources :users do
    collection do
      get :search # ユーザーの名前であいまい検索 追加分
      # get "sms_auth", to: "sms#new"
      # post "sms_auth", to: "sms#confirm"
    end
    get :search, on: :collection # ユーザーの名前であいまい検索 追加分
    # get 'subscriptions/:id/edit_favorite', to: "subscriptions#edit_favorite", as: :edit_favorite#お気に入り店舗に加えるたり外すよう
    # patch 'subscriptions/:id/update_recommend', to: "subscriptions#update_favorite", as: :update_favorite #お気に入り店舗に加えるたり外すよう
    # get 'subscriptions/favorite', to: 'subscriptions#favorite', as: :favorite_subscriptions#おすすめショップ
    resources :tickets#サブスクチケット

app/models/private_store_user_plan.rb
class PrivateStoreUserPlan < ApplicationRecord
  belongs_to :user
end

app/helpers/private_store_user_plans_helper.rb
module PrivateStoreUserPlansHelper
end

app/views/private_store_user_plans/_plan_detail.html.erb
<div class="container my-5">
  <section class="text-center dark-grey-text">
    <div class="row">
      <div class="col-lg-4 col-md-12 mb-4">
        <div class="card">
          <div class="card-body subscription-bg">
            <h5 class="mb-4"><%= @confirm_plan.nickname %></h5>
            <div class="d-flex justify-content-center">
              <img
              src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPf1fl_6GCRJUByMI9OSkIz02ssTC23yXJTQ&usqp=CAU"
              width="120"
              height="120"
            />
            </div>
            <h2 class="font-weight-bold my-4">￥<%= @confirm_plan.amount %>/月</h2>
            <p class="grey-text"><!--%= @confirm_plan.metadata.detail %--></p>
            <% if @payment.present? && @payment.amount_subtotal == @private_store_plan.amount_subtotal %>
              <button style="pointer-events: none;" class="btn btn-outline-success btn-rounded waves-effect">すでに購入されています</button>
            <% elsif current_user.customer_id.present? %>
              <p>プラン変更は出来ません。</p>
            <% else %>
              <button type="button" id="user-checkout-button" class="btn btn-outline-success btn-rounded waves-effect">サブスクする</button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/private_store_user_plans/_plans_index.html.erb
<div class="col-lg-4 col-md-6 mb-4">
  <div class="card">
    <div class="card-body subscription-bg">
      <% if (@private_store.trial == false) || (@private_store.trial == true && !current_user.select_trial) %>
        <h5 class="mb-4">加盟店プラン</h5>
        <div class="d-flex justify-content-center">
          <img
          src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPf1fl_6GCRJUByMI9OSkIz02ssTC23yXJTQ&usqp=CAU"
          width="120"
          height="120"
        />
        </div>
        <h2 class="font-weight-bold my-4"><%= "￥#{@private_store_plan.amount_subtotal.to_s(:delimited)}/月" %></h2>
        <p class="grey-text"><!--%= @private_store_plan.metadata.detail %--></p>
        <% if @pay.present? && @private_store_plan.amount_subtotal == @payment.amount_total %>
          <button style="pointer-events: none;" class="btn btn-outline-success btn-rounded waves-effect">すでに購入されています</button>
        <% else %>
          <button type="button" id="private_store-plan" class="btn btn-outline-success btn-rounded waves-effect">詳細</button>
        <% end %>
      <% else %>
	<h5 class="mb-4">トライアルプラン</h5>
        <div class="d-flex justify-content-center">
          <img
          src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPf1fl_6GCRJUByMI9OSkIz02ssTC23yXJTQ&usqp=CAU"
          width="120"
          height="120"
        />
        </div>
        <h2 class="font-weight-bold my-4"><%= "￥#{@trial_plan.amount_subtotal.to_s(:delimited)}/月" %></h2>
        <p class="grey-text"><!--%= @trial_plan.metadata.detail %--></p>
        <% if @pay.present? && @trial_plan.amount_subtotal == @payment.amount_total %>
          <button style="pointer-events: none;" class="btn btn-outline-success btn-rounded waves-effect">すでに購入されています</button>
        <% else %>
          <button type="button" id="trial-plan" class="btn btn-outline-success btn-rounded waves-effect">詳細</button>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<% if (Rails.env.development? || Rails.env.test?) && @private_store.trial == true && current_user.select_trial %>
  <script src="https://js.stripe.com/v3/"></script>
  <script>
    var stripe = Stripe("<%= ENV['STRIPE_PUBLISHABLE_KEY']%>");
    var checkoutButton = document.getElementById('trial-plan');

    checkoutButton.addEventListener('click', function() {
      stripe.redirectToCheckout({
        sessionId: '<%= @trial_plan.id %>'
      }).then(function (result) {
      });
    });
  </script>
<% elsif (Rails.env.development? || Rails.env.test?) && (@private_store.trial == false || (@private_store.trial == true && !current_user.select_trial)) %>
  <script src="https://js.stripe.com/v3/"></script>
  <script>
    var stripe = Stripe("<%= ENV['STRIPE_PUBLISHABLE_KEY']%>");
    var checkoutButton = document.getElementById('private_store-plan');

    checkoutButton.addEventListener('click', function() {
      stripe.redirectToCheckout({
        sessionId: '<%= @private_store_plan.id %>'
      }).then(function (result) {
      });
    });
  </script>


<% elsif Rails.env.production? && @private_store.trial == true && current_user.select_trial %>
  <script src="https://js.stripe.com/v3/"></script>
  <script>
    var stripe = Stripe("<%= ENV['STRIPE_PUBLISHABLE_PRODUCTION_KEY']%>");
    var checkoutButton = document.getElementById('trial-plan');

    checkoutButton.addEventListener('click', function() {
      stripe.redirectToCheckout({
        sessionId: '<%= @trial_plan.id %>'
      }).then(function (result) {
      });
    });
  </script>
<% elsif Rails.env.production? && (@private_store.trial == false || (@private_store.trial == true && !current_user.select_trial)) %>
  <script src="https://js.stripe.com/v3/"></script>
  <script>
    var stripe = Stripe("<%= ENV['STRIPE_PUBLISHABLE_PRODUCTION_KEY']%>");
    var checkoutButton = document.getElementById('private_store-plan');

    checkoutButton.addEventListener('click', function() {
      stripe.redirectToCheckout({
        sessionId: '<%= @private_store_plan.id %>'
      }).then(function (result) {
      });
    });
  </script>
<% end %>

app/views/private_store_user_plans/_plans_show.html.erb
<div class="col-lg-4 col-md-6 mb-4">
  <div class="card">
    <div class="card-body subscription-bg">
      <h5 class="mb-4">個人店舗プラン</h5>
      <div class="d-flex justify-content-center">
        <img
        src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPf1fl_6GCRJUByMI9OSkIz02ssTC23yXJTQ&usqp=CAU"
        width="120"
        height="120"
      />
      </div>
      <h2 class="font-weight-bold my-4"><%= "￥999/月" %></h2>
      <p class="grey-text"><!--%= @private_store_plan.metadata.detail %--></p>
      <% if @pay.present? && @private_store_plan.amount == @payment.amount_total %>
        <button style="pointer-events: none;" class="btn btn-outline-success btn-rounded waves-effect">すでに購入されています</button>
      <% elsif current_user.customer_id.present? %>
        <%= link_to "詳細1a", update_confirm_private_store_user_plan_path(session: @private_store_plan.id), class: "btn btn-outline-success btn-rounded waves-effect" %>
      <% else %>
	<%= link_to "詳細2a", confirm_private_store_user_plan_path(session: @private_store_plan.id), class: "btn btn-outline-success btn-rounded waves-effect" %>
      <% end %>
    </div>
  </div>
</div>


<!--div class="col-lg-4 col-md-6 mb-4">
  <div class="card">
    <div class="card-body subscription-bg">
      <h5 class="mb-4">トライアルプラン</h5>
      <div class="d-flex justify-content-center">
        <img
        src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPf1fl_6GCRJUByMI9OSkIz02ssTC23yXJTQ&usqp=CAU"
        width="120"
        height="120"
      />
      </div>

      <h2 class="font-weight-bold my-4">￥1000/3回</h2>
      <p>お試し価格で巡グルメを体験</p>
      <button type="button" id="trial-plan" class="btn btn-outline-success btn-rounded waves-effect">詳細</button>
    </div>
  </div>
</div-->

<script src="https://js.stripe.com/v3/"></script>
<script>
  var stripe = Stripe("<%= ENV['STRIPE_PUBLISHABLE_KEY']%>");

  var checkoutButton0 = document.getElementById('private-store-plan');

  checkoutButton0.addEventListener('click', function() {
    stripe.redirectToCheckout({
      sessionId: '<%= @private_store_plan.id %>'
    }).then(function (result) {
    });
  });

  
</script>

app/views/private_store_user_plans/cancel.html.erb
<h2>お支払いが失敗しました</h2>
<meta http-equiv="refresh" content=" 4; url=/">

app/views/private_store_user_plans/confirm.html.erb
<div class="container my-5">
  <section class="text-center dark-grey-text">
    <div class="row">
      <div class="col-lg-4 col-md-12 mb-4">
        <div class="card">
          <div class="card-body subscription-bg">
            <h5 class="mb-4">サンプルプラン1</h5>
            <div class="d-flex justify-content-center">
              <img
              src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPf1fl_6GCRJUByMI9OSkIz02ssTC23yXJTQ&usqp=CAU"
              width="120"
              height="120"
            />
            </div>
            <h2 class="font-weight-bold my-4">￥<%= @private_store_plan.amount_subtotal %>/月</h2>
            <p class="grey-text">サンプルコメント</p>
            <% if @payment.present? && @payment.amount_subtotal == @private_store_plan.amount_subtotal %>
              <button style="pointer-events: none;" class="btn btn-outline-success btn-rounded waves-effect">すでに購入されています</button>
            <% else %>
              <button type="button" id="user-checkout-button" class="btn btn-outline-success btn-rounded waves-effect">サブスクする</button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<script src="https://js.stripe.com/v3/"></script>
<script>
  var stripe = Stripe("<%= ENV['STRIPE_PUBLISHABLE_KEY']%>");
  var checkoutButton = document.getElementById('user-checkout-button');

  checkoutButton.addEventListener('click', function() {
    stripe.redirectToCheckout({
      sessionId: '<%= @private_store_plan.id %>'
    }).then(function (result) {
    });
  });
</script>

app/views/private_store_user_plans/edit.html.erb
<div class="container my-5">
  <section class="text-center dark-grey-text">
    <h1 class="font-weight-bold pb-2 mb-4">巡グルメ 個人店舗プラン</h1>
    <h5 class="text-muted w-responsive mx-auto mb-5">好きなプランを選択して下さい。</h5>
    <div class="row">
      <%= render "plans_index" %>
    </div>
  </section>
</div>

app/views/private_store_user_plans/new.html.erb
<div class="container my-5">
  <section class="text-center dark-grey-text">
    <h1 class="font-weight-bold pb-2 mb-4">巡グルメ 個人店舗プラン</h1>
    <div class="row">
      <%= render "plans_index" %>
    </div>
  </section>
</div>

app/views/private_store_user_plans/private_store_plan.html.erb
<div class="container my-5">
  <section class="text-center dark-grey-text">
    <% if @private_store.present? && @private_store.trial == true && current_user.select_trial %>
      <h1 class="font-weight-bold pb-2 mb-4">巡グルメ トライアルプラン</h1>
    <% else %>
      <h1 class="font-weight-bold pb-2 mb-4">巡グルメ 個人店プラン</h1>
    <% end %>
    <div class="row">
      <div class="col-lg-4 col-md-6 mb-4 mx-auto">
        <div class="card">
	  <div class="card-body subscription-bg">
            <% if @private_store.present? && @private_store.trial == true && current_user.select_trial %>
              <h5 class="mb-4">トライアルプラン</h5>
            <% else %>
              <h5 class="mb-4">個人店プラン</h5>
            <% end %>
            <div class="d-flex justify-content-center">
              <img
              src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPf1fl_6GCRJUByMI9OSkIz02ssTC23yXJTQ&usqp=CAU"
              width="120"
              height="120"
            />
            </div>
            <h2 class="font-weight-bold my-4"><%= "￥#{@plan_by_price.amount_total.to_s(:delimited)}/月" %></h2>
            <p class="grey-text"><!--%= @plan_by_price.metadata.detail %--></p>
            <% if @pay.present? && @plan_by_price.amount_total == @payment.amount_total %>
              <button style="pointer-events: none;" class="btn btn-outline-success btn-rounded waves-effect">すでに購入されています</button>
            <% else %>
              <button type="button" id="user-checkout-button" class="btn btn-outline-success btn-rounded waves-effect">サブスクする</button>
            <% end %>
	  </div>
	</div>
      </div>
    </div>
  </section>
</div>

<%
=begin%>
 <script src="https://js.stripe.com/v3/"></script>
<script>
  var stripe = Stripe("<%= ENV['STRIPE_PUBLISHABLE_KEY']%>");
  var checkoutButton = document.getElementById('user-checkout-button');

  checkoutButton.addEventListener('click', function() {
    stripe.redirectToCheckout({
      sessionId: '<%= @plan_by_price.id %>'
    }).then(function (result) {
    });
  });
</script>
<%
=end%>

<% if Rails.env.development? || Rails.env.test? %>
  <script src="https://js.stripe.com/v3/"></script>
  <script>
    var stripe = Stripe("<%= ENV['STRIPE_PUBLISHABLE_KEY']%>");
    var checkoutButton = document.getElementById('user-checkout-button');

    checkoutButton.addEventListener('click', function() {
      stripe.redirectToCheckout({
        sessionId: '<%= @plan_by_price.id %>'
      }).then(function (result) {
      });
    });
  </script>
<% end %>

<% if Rails.env.production? %>
  <script src="https://js.stripe.com/v3/"></script>
  <script>
    var stripe = Stripe("<%= ENV['STRIPE_PUBLISHABLE_PRODUCTION_KEY']%>");
    var checkoutButton = document.getElementById('user-checkout-button');

    checkoutButton.addEventListener('click', function() {
      stripe.redirectToCheckout({
        sessionId: '<%= @plan_by_price.id %>'
      }).then(function (result) {
      });
    });
  </script>
<% end %>

app/views/private_store_user_plans/success.html.erb
<h1>お支払いが成功しました</h1>
<meta http-equiv="refresh" content=" 4; url=/">

app/views/private_store_user_plans/update_confirm.html.erb
<%= render "plan_detail" %>