config/routes.rb
Rails.application.routes.draw do

  get 'ticket_logs' => "ticket_logs#index", as: :ticket_logs#チケット使用履歴
  delete "ticket_logs", to: "ticket_logs#destroy", as: 'logs_destroy'
  get 'ticket' => "tickets#user_have_ticket", as: :user_have_ticket#チケット使用履歴

  root 'static_pages#top'#トップページ
  get 'paypaytest' => "static_pages#paypaytest"#paypaytest
  get 'top_owner' => "static_pages#top_owner"#経営者様トップページ
  get 'top_user' => "static_pages#top_user"#利用者様トップページ
  get 'megurume_line' => "static_pages#megurume_line"#LINE誘導
  get 'discussion' => "static_pages#discussion"#相談窓口
  get 'specified_commercial_transaction_law' => "static_pages#specified_commercial_transaction_law"#特定商取引法
  get 'how_to_use' => "subscriptions#how_to_use", as: :how_to_use#ご利用方法について
  get 'plan_description' => "subscriptions#plan_description", as: :plan_description#プラン説明
  get 'kiyaku' => "subscriptions#kiyaku", as: :kiyaku#利用規約
  get 'privacy_policy' => "subscriptions#privacy_policy", as: :privacy_policy#プライバシーポリシー
  get 'site' => "subscriptions#site", as: :site#サイトについて
  get 'company_profile' => "subscriptions#company_profile", as: :company_profile#会社概要

  get 'subscriptions/setup', to: 'subscriptions#setup', as: :setup_subscriptions#経営者のプラン内容
  get '/cancel', to: 'user_plans#cancel'
  get '/success', to: 'user_plans#success'
  get '/private_store_cancel', to: 'private_store_user_plans#cancel'
  get '/private_store_success', to: 'private_store_user_plans#success'

  get 'categories/shop_list', to: 'categories#shop_list', as: :shop_list_categories
  get 'categories/recommend', to: 'categories#recommend', as: :recommend_categories#おすすめショップ

  get 'subscriptions/show_sample', to: 'subscriptions#show_sample', as: :show_sample_subscriptions
  get 'subscriptions/shop_case', to: 'subscriptions#shop_case', as: :shop_case#ショップ事例

  get 'subscriptions/:id/ticket', to: 'users#ticket', as: :use_ticket #チケット発行ページ
  get 'private_store/:id/ticket', to: 'private_store_users#ticket', as: :private_store_use_ticket #private_store用チケット発行ページ
  get 'private_store/:id/new_ticket', to: 'private_store_user_plans#new', as: :private_store_new_ticket #private_store用サブスクを始める
  get 'subscription/:id/new_ticket', to: 'user_plans#new', as: :subscription_new_ticket #subscription用サブスクを始める

  get '/subscriptions/:subscription_id/subscription_reviews', to: 'reviews#subscription_reviews', as: :subscription_reviews #サブスクレビューページ
  get '/private_stores/:private_store_id/private_store_reviews', to: 'reviews#private_store_reviews', as: :private_store_reviews #個人店舗レビューページ
  get '/subscriptions/:subscription_id/edit_subscription_reviews/:id', to: 'reviews#edit_subscription_reviews', as: :edit_subscription_reviews #サブスクレビューページ

  get '/ticket_success', to: 'tickets#ticket_success', as: :ticket_success
  patch 'users/:user_id/tickets/:id/ticket_update_after_second_time', to: 'tickets#ticket_update_after_second_time', as: :ticket_update_after_second_time
  patch 'users/:user_id/tickets/:id/edit_user_ticket', to: 'tickets#edit_user_ticket', as: :edit_user_ticket

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, path: 'users', controllers: {
   # omniauth_callbacks:  'users/omniauth_callbacks',
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/sign_up/confirm', to: 'users/registrations#confirm'
    patch 'users/sign_up/complete', to: 'users/registrations#complete'
    post 'users/sign_up/complete', to: 'users/registrations#complete'
    get "/devise/auth/facebook/callback" => "users/omniauth_callbacks#facebook"
    get "/devise/auth/twitter/callback" => "users/omniauth_callbacks#twitter"
    match "/users/auth/line" => "users/omniauth_callbacks#passthru", via: [:get, :post]
    match "/users/auth/line/callback" => "users/omniauth_callbacks#line", via: [:get, :post]
    get 'users/sign_up', to: 'users#new'
  end

  devise_for :owners, path: 'owners', controllers: {
    sessions:      'owners/sessions',
    passwords:     'owners/passwords',
    registrations: 'owners/registrations'
  }
  devise_scope :owner do
    get "/devise/auth/facebook_owner/callback" => "owners/omniauth_callbacks#facebook_owner"
    get "/devise/auth/twitter_owner/callback" => "owners/omniauth_callbacks#twitter_owner"
    match "/owners/auth/line" => "owners/omniauth_callbacks#passthru", via: [:get, :post]
    match "/owners/auth/line/callback" => "owners/omniauth_callbacks#line_owner", via: [:get, :post]
  end

  devise_scope :owner do
    post 'owners/sign_up/confirm', to: 'owners/registrations#confirm'
    patch 'owners/sign_up/complete', to: 'owners/registrations#complete'
    post 'owners/sign_up/complete', to: 'owners/registrations#complete'
  end

  resource :admin, except: %i(new create destroy) do
    get 'account', on: :collection #アカウントページ
    member do
      get 'private_owner_edit'
      patch 'private_owner_update'
      get 'subscription_owner_edit'
      patch 'subscription_owner_update'
      # patch 'private_stores/:private_stores_id/private_owner_update', to: 'admins#private_owner_update', as: :private_owner_update
      get 'owner_edit' #個人情報編集
      patch 'owner_update' #個人情報編集
      get 'user_edit' #
      patch 'user_update' #
    end
  end
  resources :blogs#管理者が書くサブスクnews
  get 'reviews/list' => "reviews#list"#利用者ではない人用の表示ページ
  get 'subscriptions/list' => "subscriptions#list"#まだ決まってない。使わないかもしれない
  get 'blogs/index'#まだ決まってない。使わないかもしれない

  get 'suports', to: "suports#index"#サポート画面
  post 'suports/confirm' => "suports#confirm"#サポート確認画面
  post 'suports/thanks' => "suports#thanks"#サポート完了通知仮面

  get 'contacts', to: "contacts#index"#お問い合わせ画面
  post 'contacts/confirm' => "contacts#confirm"#お問い合わせ確認画面
  post 'contacts/thanks' => "contacts#thanks"#お問い合わせ完了通知仮面

  resources :medias#メディア
  resources :interviews#経営者様インタビュー
  resources :cupons#クーポン
  resources :products#QRコード

  get 'owners/deleted_owners'#論理削除された経営者
  resources :owners do
    get :search, on: :collection #オーナーの名前であいまい検索 追加分
    get :subscription_private_store_select, on: :member #加盟店か個人店かの選択
    get :subscription_private_store_judging_select, on: :member #加盟店か個人店かの選択と審査の選択
    member do
      post "thanks" #会員登録完了通知画面
      get 'owner_account' #アカウントページ
      patch 'update_deleted_owners' #アカウントページ論理削除
    end
    resources :subscriptions do
      get 'like_lunch', on: :member
      member do
        get 'edit_recommend' #おすすめ追加よう
        patch 'update_recommend' #おすすめ店舗に加えるたり外すよう
        get '/owner_subscriptions', to: "subscriptions#owner_subscriptions", as: :owner_subscriptions
        post :takeout
      end
    end
    resources :private_stores do
      resources :images
      member do
        get 'edit_recommend' #おすすめ追加よう
        patch 'update_recommend' #おすすめ店舗に加えるたり外すよう
        #get "confirm", to: "private_store_user_plans#confirm"
        #get "update_confirm", to: "private_store_user_plans#update_confirm"
        #get 'plans_new', to: "private_store_user_plans#new", as: 'plans_new' #利用者のプラン内容
        #get "plans_edit", to: "private_store_user_plans#edit", as: 'plans_edit'
              #patch "plans_update", to: "private_store_user_plans#update", as: 'plans_update'
        #delete "plans_destroy", to: "private_store_user_plans#destroy", as: 'plans_destroy'
        get '/owner_private_stores', to: "private_stores#owner_private_stores", as: :owner_private_stores
        post :takeout
      end
    end
  end
  resources :maps
  resources :categories, only: %i(index) do
    get 'like_lunch', on: :member
    post 'search', on: :collection
  end
  get 'categories/trial_shop', to: 'categories#trial_shop', as: :trial_shop#トライアルのお店一覧
  get 'private_stores/private_all_shop', to: 'private_stores#private_all_shop', as: :private_all_shop#個人店舗のお店一覧
  get 'subscriptions/subscription_all_shop', to: 'subscriptions#subscription_all_shop', as: :subscription_all_shop#加盟店舗のお店一覧
  post 'subscriptions/subscription_confirm', to: 'subscriptions#subscription_confirm', as: :subscription_confirm#加盟店舗の審査の確認画面
  patch 'subscriptions/subscription_judging', to: 'subscriptions#subscription_judging'#加盟店舗の審査
  post 'subscriptions/subscription_judging', to: 'subscriptions#subscription_judging'#加盟店舗の審査

  post 'private_stores/private_store_confirm', to: 'private_stores#private_store_confirm', as: :private_store_confirm#個人店舗の審査の確認画面
  patch 'private_stores/private_store_judging', to: 'private_stores#private_store_judging'#個人店舗の審査
  post 'private_stores/private_store_judging', to: 'private_stores#private_store_judging'#個人店舗の審査

  get 'users/user_subscription_email', to: 'users#user_subscription_email' #加盟店の利用者から経営者へメール
  patch 'users/user_subscription_confirm', to: 'users#user_subscription_confirm'
  patch 'users/user_subscription_thanks', to: 'users#user_subscription_thanks'
  post 'users/user_subscription_thanks', to: 'users#user_subscription_thanks'

  get 'users/user_private_store_email', to: 'users#user_private_store_email' #加盟店の利用者から経営者へメール
  patch 'users/user_private_store_confirm', to: 'users#user_private_store_confirm'
  patch 'users/user_private_store_thanks', to: 'users#user_private_store_thanks'
  post 'users/user_private_store_thanks', to: 'users#user_private_store_thanks'

  get 'users/deleted_users'##論理削除された利用者
  resources :users do
    collection do
      get :search # ユーザーの名前であいまい検索 追加分
      # get "sms_auth", to: "sms#new"
      # post "sms_auth", to: "sms#confirm"
    end
    get :search, on: :collection # ユーザーの名前であいまい検索 追加分
    # get 'subscriptions/:id/edit_favorite', to: "subscriptions#edit_favorite", as: :edit_favorite#お気に入り店舗に加えるたり外すよう
    # patch 'subscriptions/:id/update_recommend', to: "subscriptions#update_favorite", as: :update_favorite #お気に入り店舗に加えるたり外すよう
    # get 'subscriptions/favorite', to: 'subscriptions#favorite', as: :favorite_subscriptions#おすすめショップ
    resources :tickets#サブスクチケット

app/models/shop.rb
class Shop < ApplicationRecord
  # belongs_to :owner
  # has_one :subscription, dependent: :destroy #shop_idを追加で１対１の関係

  enum monthly_fee: { "1980"=> 1, "4980"=> 2, "19800"=> 3}
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  before_action :set_owner, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  before_action :set_subscription, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to new_owner_shop_subscription_url(@owner, @shop), notice: 'Shop was successfully created.' }
        format.json { render :index, status: :created, location: @shop }

        @owner.subscriptions.update(
          owner_id: @shop.owner_id,
          shop_id: @shop.id
        )
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to new_owner_shop_subscription_url(@owner, @shop), notice: 'Shop was successfully updated.' }
        format.json { render :index, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to owner_shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    def set_owner
      @owner = Owner.find(params[:owner_id])
    end

    def set_subscription
      @subscription = Subscription.find_by(params[:subscription_id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:phone_number, :store_information, :payee, :line_id, :address, :owner_id)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_name %>
    <%= form.text_field :category_name, id: :shop_category_name, placeholder: "例)カレー", class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :monthly_fee %>
    <%= form.select :monthly_fee, Shop.monthly_fees.keys, { include_blank: true }, placeholder: "例)利用料金を選択してください", class: 'form-control' %>
  </div>

  <%
=begin%>
 <div class="field">
    <%= form.label :電話番号 %>
    <%= shop.phone_number %>
  </div>

  <div class="field">
    <%= form.label :店舗情報 %>
    <%= form.text_area :store_information, id: :shop_store_information %>
  </div>

  <div class="field">
    <%= form.label :振込先 %>
    <%= form.text_field :payee, id: :shop_payee %>
  </div>

  <div class="field">
    <%= form.label :LineID %>
    <%= form.text_field :line_id, id: :shop_line_id %>
  </div>

  <div class="field">
    <%= form.label :お店の場所 %>
    <%= form.text_field :address, id: :shop_address %>
  </div>
  <% 
 <div class="field">
    <%= form.label :店主名 %>
    <%= form.hidden_field :owner_id, :value => @owner.owner_id %>
    <%= form.text_field :owner_id, id: :shop_owner_id %>
  </div> 
<%
=end%>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<% provide(:title, "お店の編集") %>

<h1>Editing Shop</h1>

<%= form_with(model: @shop, url: owner_shop_path, local: true) do |form| %>
  <%= render 'shared/error_messages' , object: @shop %>

 <div class="field">
    <%= form.label :電話番号 %>
    <%= shop.phone_number %>
  </div>

  <div class="field">
    <%= form.label :店舗情報 %>
    <%= form.text_area :store_information, id: :shop_store_information %>
  </div>

  <div class="field">
    <%= form.label :振込先 %>
    <%= form.text_field :payee, id: :shop_payee %>
  </div>

  <div class="field">
    <%= form.label :LineID %>
    <%= form.text_field :line_id, id: :shop_line_id %>
  </div>

  <div class="field">
    <%= form.label :お店の場所 %>
    <%= form.text_field :address, id: :shop_address %>
  </div>
  <% 
<%
=end%>
  <%= form.hidden_field :owner_id, :value => @owner.id %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', owner_shop_path(@shop, owner_id:@owner.id) %> |
<%= link_to 'Back', owner_shops_path %>

app/views/shops/index.html.erb
<% provide(:title, "お店一覧") %>

<h1>Shops</h1>
<table>
  <tbody>
    <% @shops.each do |shop| %>
    <hr class="tool-bar">
      <div class="row">
        <div class="col-md-8">
          <%= shop.owner_id %>
        </div>

        <div class="col-md-1 tool--item">
          <%= link_to "詳細", owner_shop_path(shop, owner_id:@owner.id), class: "btn-gradient-3d-simple" %>
        </div>
        <div class="col-md-1 tool--item">
          <%= link_to "編集", edit_owner_shop_path(shop, owner_id:@owner.id), class: "btn-gradient-3d-simple" %>
        </div>
        <div class="col-md-1 btn--del">
          <%= link_to "削除", owner_shop_path(shop, owner_id:@owner.id), method: :delete, class: "btn btn-danger", data: { confirm: "お店を削除してよろしいですか？" } %>
        </div>
      </div>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Shop', new_owner_shop_path, class: "btn btn-info" %>

app/views/shops/new.html.erb
<% provide(:title, "ショップ開設") %>

<h1>ショップ開設</h1>

<%= form_with(model: @shop, url: owner_shops_path, local: true) do |form| %>
  <%= render 'shared/error_messages' , object: @shop %>

  <%= form.hidden_field :owner_id, :value => @owner.id %>

  <div class="field">
    <%= form.label :monthly_fee %>
    <%= form.select :monthly_fee, Shop.monthly_fees.keys, { include_blank: true }, placeholder: "利用料金を選択してください", class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, placeholder: "例)", class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'ショップ一覧', owner_shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<% provide(:title, 'Shop Show') %>
<h1>お店詳細</h1>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <table class="table table-bordered" id="table-schedule">
        <tbody>
          <tr>
            <th class="active center">
              <p>
              <span><%= Shop.human_attribute_name :category_name %></span>
              <span><td class="active"><%= @shop.category_name %></span></td>
              <br><th class="active center"><span><%= Shop.human_attribute_name :monthly_fee %></span></th>
              <span><td class="active"><%= @shop.monthly_fee %></span></td>
              </p>
            </th>
          </tr>
          <tr>
            <th class="active center col-md-2"><%= Shop.human_attribute_name :store_information %></th>
            <td  class="active" colspan = "3"><%= @shop.store_information %></td>
          </tr>
        </tbody>
          <div class="tool--item">
            <%= link_to "編集", edit_owner_shop_path(@shop, owner_id:@owner.id), class: "btn-gradient-3d-simple" %>
            <%= link_to "削除", owner_shop_path(@shop, owner_id:@owner.id), method: :delete, class: "btn btn-danger", data: { confirm: "お店を削除してよろしいですか？" } %>
          </div>
      </table>
    </div>    
  </div>

<%= link_to 'Back', owner_shops_path %>