config/routes.rb
Rails.application.routes.draw do

  get 'ticket_logs' => "ticket_logs#index", as: :ticket_logs#チケット使用履歴
  delete "ticket_logs", to: "ticket_logs#destroy", as: 'logs_destroy'
  get 'ticket' => "tickets#user_have_ticket", as: :user_have_ticket#チケット使用履歴

  root 'static_pages#top'#トップページ
  get 'paypaytest' => "static_pages#paypaytest"#paypaytest
  get 'top_owner' => "static_pages#top_owner"#経営者様トップページ
  get 'top_user' => "static_pages#top_user"#利用者様トップページ
  get 'megurume_line' => "static_pages#megurume_line"#LINE誘導
  get 'discussion' => "static_pages#discussion"#相談窓口
  get 'specified_commercial_transaction_law' => "static_pages#specified_commercial_transaction_law"#特定商取引法
  get 'how_to_use' => "subscriptions#how_to_use", as: :how_to_use#ご利用方法について
  get 'plan_description' => "subscriptions#plan_description", as: :plan_description#プラン説明
  get 'kiyaku' => "subscriptions#kiyaku", as: :kiyaku#利用規約
  get 'privacy_policy' => "subscriptions#privacy_policy", as: :privacy_policy#プライバシーポリシー
  get 'site' => "subscriptions#site", as: :site#サイトについて
  get 'company_profile' => "subscriptions#company_profile", as: :company_profile#会社概要

  get 'subscriptions/setup', to: 'subscriptions#setup', as: :setup_subscriptions#経営者のプラン内容
  get '/cancel', to: 'user_plans#cancel'
  get '/success', to: 'user_plans#success'
  get '/private_store_cancel', to: 'private_store_user_plans#cancel'
  get '/private_store_success', to: 'private_store_user_plans#success'

  get 'categories/shop_list', to: 'categories#shop_list', as: :shop_list_categories
  get 'categories/recommend', to: 'categories#recommend', as: :recommend_categories#おすすめショップ

  get 'subscriptions/show_sample', to: 'subscriptions#show_sample', as: :show_sample_subscriptions
  get 'subscriptions/shop_case', to: 'subscriptions#shop_case', as: :shop_case#ショップ事例

  get 'subscriptions/:id/ticket', to: 'users#ticket', as: :use_ticket #チケット発行ページ
  get 'private_store/:id/ticket', to: 'private_store_users#ticket', as: :private_store_use_ticket #private_store用チケット発行ページ
  get 'private_store/:id/new_ticket', to: 'private_store_user_plans#new', as: :private_store_new_ticket #private_store用サブスクを始める
  get 'subscription/:id/new_ticket', to: 'user_plans#new', as: :subscription_new_ticket #subscription用サブスクを始める

  get '/subscriptions/:subscription_id/subscription_reviews', to: 'reviews#subscription_reviews', as: :subscription_reviews #サブスクレビューページ
  get '/private_stores/:private_store_id/private_store_reviews', to: 'reviews#private_store_reviews', as: :private_store_reviews #個人店舗レビューページ
  get '/subscriptions/:subscription_id/edit_subscription_reviews/:id', to: 'reviews#edit_subscription_reviews', as: :edit_subscription_reviews #サブスクレビューページ

  get '/ticket_success', to: 'tickets#ticket_success', as: :ticket_success
  patch 'users/:user_id/tickets/:id/ticket_update_after_second_time', to: 'tickets#ticket_update_after_second_time', as: :ticket_update_after_second_time
  patch 'users/:user_id/tickets/:id/edit_user_ticket', to: 'tickets#edit_user_ticket', as: :edit_user_ticket

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, path: 'users', controllers: {
   # omniauth_callbacks:  'users/omniauth_callbacks',
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/sign_up/confirm', to: 'users/registrations#confirm'
    patch 'users/sign_up/complete', to: 'users/registrations#complete'
    post 'users/sign_up/complete', to: 'users/registrations#complete'
    get "/devise/auth/facebook/callback" => "users/omniauth_callbacks#facebook"
    get "/devise/auth/twitter/callback" => "users/omniauth_callbacks#twitter"
    match "/users/auth/line" => "users/omniauth_callbacks#passthru", via: [:get, :post]
    match "/users/auth/line/callback" => "users/omniauth_callbacks#line", via: [:get, :post]
    get 'users/sign_up', to: 'users#new'
  end

  devise_for :owners, path: 'owners', controllers: {
    sessions:      'owners/sessions',
    passwords:     'owners/passwords',
    registrations: 'owners/registrations'
  }
  devise_scope :owner do
    get "/devise/auth/facebook_owner/callback" => "owners/omniauth_callbacks#facebook_owner"
    get "/devise/auth/twitter_owner/callback" => "owners/omniauth_callbacks#twitter_owner"
    match "/owners/auth/line" => "owners/omniauth_callbacks#passthru", via: [:get, :post]
    match "/owners/auth/line/callback" => "owners/omniauth_callbacks#line_owner", via: [:get, :post]
  end

  devise_scope :owner do
    post 'owners/sign_up/confirm', to: 'owners/registrations#confirm'
    patch 'owners/sign_up/complete', to: 'owners/registrations#complete'
    post 'owners/sign_up/complete', to: 'owners/registrations#complete'
  end

  resource :admin, except: %i(new create destroy) do
    get 'account', on: :collection #アカウントページ
    member do
      get 'private_owner_edit'
      patch 'private_owner_update'
      get 'subscription_owner_edit'
      patch 'subscription_owner_update'
      # patch 'private_stores/:private_stores_id/private_owner_update', to: 'admins#private_owner_update', as: :private_owner_update
      get 'owner_edit' #個人情報編集
      patch 'owner_update' #個人情報編集
      get 'user_edit' #
      patch 'user_update' #
    end
  end
  resources :blogs#管理者が書くサブスクnews
  get 'reviews/list' => "reviews#list"#利用者ではない人用の表示ページ
  get 'subscriptions/list' => "subscriptions#list"#まだ決まってない。使わないかもしれない
  get 'blogs/index'#まだ決まってない。使わないかもしれない

  get 'suports', to: "suports#index"#サポート画面
  post 'suports/confirm' => "suports#confirm"#サポート確認画面
  post 'suports/thanks' => "suports#thanks"#サポート完了通知仮面

  get 'contacts', to: "contacts#index"#お問い合わせ画面
  post 'contacts/confirm' => "contacts#confirm"#お問い合わせ確認画面
  post 'contacts/thanks' => "contacts#thanks"#お問い合わせ完了通知仮面

  resources :medias#メディア
  resources :interviews#経営者様インタビュー
  resources :cupons#クーポン
  resources :products#QRコード

  get 'owners/deleted_owners'#論理削除された経営者
  resources :owners do
    get :search, on: :collection #オーナーの名前であいまい検索 追加分
    get :subscription_private_store_select, on: :member #加盟店か個人店かの選択
    get :subscription_private_store_judging_select, on: :member #加盟店か個人店かの選択と審査の選択
    member do
      post "thanks" #会員登録完了通知画面
      get 'owner_account' #アカウントページ
      patch 'update_deleted_owners' #アカウントページ論理削除
    end
    resources :subscriptions do
      get 'like_lunch', on: :member
      member do
        get 'edit_recommend' #おすすめ追加よう
        patch 'update_recommend' #おすすめ店舗に加えるたり外すよう
        get '/owner_subscriptions', to: "subscriptions#owner_subscriptions", as: :owner_subscriptions
        post :takeout
      end
    end
    resources :private_stores do
      resources :images
      member do
        get 'edit_recommend' #おすすめ追加よう
        patch 'update_recommend' #おすすめ店舗に加えるたり外すよう
        #get "confirm", to: "private_store_user_plans#confirm"
        #get "update_confirm", to: "private_store_user_plans#update_confirm"
        #get 'plans_new', to: "private_store_user_plans#new", as: 'plans_new' #利用者のプラン内容
        #get "plans_edit", to: "private_store_user_plans#edit", as: 'plans_edit'
              #patch "plans_update", to: "private_store_user_plans#update", as: 'plans_update'
        #delete "plans_destroy", to: "private_store_user_plans#destroy", as: 'plans_destroy'
        get '/owner_private_stores', to: "private_stores#owner_private_stores", as: :owner_private_stores
        post :takeout
      end
    end
  end
  resources :maps
  resources :categories, only: %i(index) do
    get 'like_lunch', on: :member
    post 'search', on: :collection
  end
  get 'categories/trial_shop', to: 'categories#trial_shop', as: :trial_shop#トライアルのお店一覧
  get 'private_stores/private_all_shop', to: 'private_stores#private_all_shop', as: :private_all_shop#個人店舗のお店一覧
  get 'subscriptions/subscription_all_shop', to: 'subscriptions#subscription_all_shop', as: :subscription_all_shop#加盟店舗のお店一覧
  post 'subscriptions/subscription_confirm', to: 'subscriptions#subscription_confirm', as: :subscription_confirm#加盟店舗の審査の確認画面
  patch 'subscriptions/subscription_judging', to: 'subscriptions#subscription_judging'#加盟店舗の審査
  post 'subscriptions/subscription_judging', to: 'subscriptions#subscription_judging'#加盟店舗の審査

  post 'private_stores/private_store_confirm', to: 'private_stores#private_store_confirm', as: :private_store_confirm#個人店舗の審査の確認画面
  patch 'private_stores/private_store_judging', to: 'private_stores#private_store_judging'#個人店舗の審査
  post 'private_stores/private_store_judging', to: 'private_stores#private_store_judging'#個人店舗の審査

  get 'users/user_subscription_email', to: 'users#user_subscription_email' #加盟店の利用者から経営者へメール
  patch 'users/user_subscription_confirm', to: 'users#user_subscription_confirm'
  patch 'users/user_subscription_thanks', to: 'users#user_subscription_thanks'
  post 'users/user_subscription_thanks', to: 'users#user_subscription_thanks'

  get 'users/user_private_store_email', to: 'users#user_private_store_email' #加盟店の利用者から経営者へメール
  patch 'users/user_private_store_confirm', to: 'users#user_private_store_confirm'
  patch 'users/user_private_store_thanks', to: 'users#user_private_store_thanks'
  post 'users/user_private_store_thanks', to: 'users#user_private_store_thanks'

  get 'users/deleted_users'##論理削除された利用者
  resources :users do
    collection do
      get :search # ユーザーの名前であいまい検索 追加分
      # get "sms_auth", to: "sms#new"
      # post "sms_auth", to: "sms#confirm"
    end
    get :search, on: :collection # ユーザーの名前であいまい検索 追加分
    # get 'subscriptions/:id/edit_favorite', to: "subscriptions#edit_favorite", as: :edit_favorite#お気に入り店舗に加えるたり外すよう
    # patch 'subscriptions/:id/update_recommend', to: "subscriptions#update_favorite", as: :update_favorite #お気に入り店舗に加えるたり外すよう
    # get 'subscriptions/favorite', to: 'subscriptions#favorite', as: :favorite_subscriptions#おすすめショップ
    resources :tickets#サブスクチケット

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :owner
  # belongs_to :user, optional: true#belongs_toの外部キーのnilを許可
  belongs_to :category, optional: true#belongs_toの外部キーのnilを許可
  # has_many :category_subscriptions, dependent: :destroy
  # has_many :categories, through: :category_subscriptions
  # accepts_nested_attributes_for :categories, allow_destroy: true

  has_many :reviews, dependent: :destroy
  has_many :instablogs, dependent: :destroy
  
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name, length: { maximum: 50 }
  validates :address, length: { maximum: 1000 }, on: :update
  validates :title, length: { maximum: 100 }, on: :update
  validates :detail, length: { maximum: 100 }, on: :update
  validates :subscription_detail, length: { maximum: 1000 }, on: :update
  # validates :category_id, presence: true, on: :update
  # validates :price, presence: true, on: :update


  geocoded_by :address
  after_validation :geocode

  enum price: { "1000" => 0, "3000"=> 1, "9000"=> 2, "11000"=> 3, "18000"=> 4, "25000"=> 5, "50000"=> 6, "100000"=> 7}, _prefix: true
  # attachment :image_subscription
  mount_uploader :image_subscription, SubscriptionUploader
  mount_uploader :sub_image, SubscriptionUploader
  mount_uploader :sub_image2, SubscriptionUploader
  mount_uploader :sub_image3, SubscriptionUploader
  mount_uploader :sub_image4, SubscriptionUploader
  mount_uploader :sub_image5, SubscriptionUploader
  mount_uploader :sub_image6, SubscriptionUploader
  mount_uploader :sub_image7, SubscriptionUploader
  mount_uploader :sub_image8, SubscriptionUploader
  mount_uploader :sub_image9, SubscriptionUploader
  mount_uploader :sub_image10, SubscriptionUploader
  mount_uploader :sub_image11, SubscriptionUploader
  mount_uploader :sub_image12, SubscriptionUploader
  mount_uploader :qr_image, SubscriptionUploader



  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/edit.html.erb
<% provide(:title, "サブスクページ編集") %>

<h1 class="brand-color display-4 mt-6 mb-6">加盟店サブスクページ編集</h1>

<%= form_with(model: @subscription, url: owner_subscription_path(@subscription, owner_id: @owner.id), multipart: true, local: true) do |form| %>
  <%= render 'shared/error_messages' , object: @subscription %>

  <%= form.hidden_field :owner_id, :value => @owner.id %>

  <div class="field">
    <%= form.label :お店の名前 %> <span class="must">必須</span>
    <%= form.text_field :name, :required => true, class: 'form-control form_border' %>
  </div>

  <div class="field">
    <%= form.label :サイトURL %> <span class="must">必須</span><br/>
    <%= form.text_field :site, :required => true, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :サブスク料理名 %> <span class="must">必須</span>
    <%= form.text_field :title, :required => true, id: :subscription_title, class: 'form-control form_border' %>
  </div>

  <div class="field">
    <%= form.label :お店専用メールアドレス %><span class="must">お客様に公開されるメールアドレスです</span><br/>
    <%= form.email_field :email, :required => true, placeholder: "sample@gmail.com", autofocus: true, autocomplete: "email", class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :お店専用の電話番号 %> <span>＊(ハイフンなし)連絡がつく番号でお願いします。</span><span class="must">お客様に公開される電話番号です</span><br/>
    <%= form.telephone_field :phone_number, :required => true, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :お店の住所 %> <span class="must">必須</span>
    <%= form.text_field :address, :required => true, class: 'form-control form_border' %>
  </div>

  <div class="field">
    <%= form.label :商品説明 %> <span class="must">必須</span>
    <%= form.text_area :detail, :required => true, class: 'form-control form_border' %>
  </div>

  <div class="field">
    <%= form.label :"LINE@QRコード画像", for: "file-input", type:"file" %><span class="must">必須</span><br/>
    <%= form.file_field :qr_image, id: "file-input" %>
  </div>

  <div class="field">
    <%= form.label :お店トップ紹介写真, for: "file-input", type:"file"%> <span class="must">必須</span><br/>
    <%= form.file_field :image_subscription, id: "file-input" %>
  </div>

  <div class="field">
    <%= form.label :店舗情報 %>
    <%= form.text_area :subscription_detail, :required => true, placeholder: "例)", class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :サブのお店紹介写真, for: "file-input", type:"file" %><br/>
    <%= form.file_field :sub_image, id: "file-input" %>
  </div>

  <div class="field">
    <%= form.label :サブのお店紹介写真2, for: "file-input", type:"file" %><br/>
    <%= form.file_field :sub_image2, id: "file-input" %>
  </div>

  <div class="field">
    <%= form.label :サブのお店紹介写真3, for: "file-input", type:"file" %><br/>
    <%= form.file_field :sub_image3, id: "file-input" %>
  </div>

  <div class="field">
    <%= form.label :サブのお店紹介写真4, for: "file-input", type:"file" %><br/>
    <%= form.file_field :sub_image4, id: "file-input" %>
  </div>

  <div class="field">
    <%= form.label :サブのお店紹介写真5, for: "file-input", type:"file" %><br/>
    <%= form.file_field :sub_image5, id: "file-input" %>
  </div>

  <div class="field">
    <%= form.label :サブのお店紹介写真6, for: "file-input", type:"file" %><br/>
    <%= form.file_field :sub_image6, id: "file-input" %>
  </div>

  <div class="field">
    <%= form.label :サブのお店紹介写真7, for: "file-input", type:"file" %><br/>
    <%= form.file_field :sub_image7, id: "file-input" %>
  </div>

  <div class="field">
    <%= form.label :サブのお店紹介写真8, for: "file-input", type:"file" %><br/>
    <%= form.file_field :sub_image8, id: "file-input" %>
  </div>

  <div class="field">
    <%= form.label :サブのお店紹介写真9, for: "file-input", type:"file" %><br/>
    <%= form.file_field :sub_image9, id: "file-input"%>
  </div>

  <div class="field">
    <%= form.label :カテゴリ %> <span class="must">必須</span><br/>
    <%= form.collection_select(:category_id, Category.all, :id, :name, include_blank: "カテゴリを選択してください", :required => true, class: 'form-control') %>
  </div>

  <div class="field">
    <%= form.label :加入プラン %> <span class="must">必須</span><br/>
    <%= form.select :price, Subscription.prices.keys, { include_blank: "加入するプランを選択してください"}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :trial %>
    <%= form.select :trial, [['不参加', false],['参加', true]], { selected: false }, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label "テイクアウト" %><br>
    <%= form.select :takeout, [['不可', false],['可', true]], { selected: @subscription.takeout }, class: 'form-control col-sm-2' %>
  </div>

  <div class="field">
    <%= form.label "準備にかかる時間の目安(分)" %>
    <%= form.number_field :preparation_time, value: @subscription.preparation_time, class: 'form-control col-sm-2' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %></br>

<h1>instagram 投稿</h1>

<%= form_with(model: @instablog, url: instablogs_path, local: true) do |form| %>

  <%= form.hidden_field :subscription_id, :value => @subscription.id %>

  <div class="field">
    <%= form.label :埋め込みコード %>
    <%= form.text_area :insta_content, placeholder: "こちらにコピーしたinstagram埋め込みコードを添付してください。", class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "投稿する" %>
  </div>

  <%= "※instagram埋め込みコードの取得方法がわからない場合はこちらを参照して下さい。" %> <%= link_to '➡︎(参照資料)', 'https://appllio.com/instagram-embed-code-post', target: :_blank %>

<% end %></br>

<div class="mt-5 mb-8">
  <%= link_to '詳細', owner_subscription_path(@subscription, owner_id: @owner.id), class: "btn btn-brand" %>
  <%= link_to '一覧へ', owner_subscriptions_path, class: "btn btn-brand" %>
</div>

  <%
=begin%>
 <div class="field">
    <%= form.label :カテゴリ %> <span class="must">必須</span><br/>
    <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name, multiple: true)  do |t| %>
      <% t.label   { t.check_box + t.text } %>
    <% end %>
  </div>
<%
=end%>

app/views/subscriptions/favorite.html.erb
<h1>お気に入り店舗</h1>


<% @subscriptions.each do |subscription| %>
  <% if current_user.id == subscription.user_id %>
    <div class="container mt-5">
      <section class="dark-grey-text">
        <div class="row align-items-center">
          <div class="col-lg-5 col-xl-3">
            <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
              <% if subscription.image_subscription.present? %>
                <%= image_tag subscription.image_subscription_url, width: '100%' %>
              <% else %>
                <p>なし</p>
              <% end %>
            </div>
          </div>
          <div class="col-lg-7 col-xl-8">
            <h4 class="font-weight-bold mb-3"><strong><%= subscription.name %></strong></h4>
            <p class="dark-grey-text"><%= subscription.title %></p>
            <%= link_to "サブスクしてみる", owner_subscription_path(id: subscription.id, owner_id: subscription.owner_id), class: 'btn btn-outline-primary btn-rounded text-primary' %>
          </div>
        </div>
        <hr class="my-3">
      </section>
    </div>
  <% end%>
<% end%>

app/views/subscriptions/how_to_use.html.erb
<% provide(:title, "ご利用方法") %>
<%= image_tag 'how-to-use.png', Style: "height: 300px"%>

app/views/subscriptions/map.js.erb
/* 
index.html.erbのscript内に
google mapのインスタンス変数である、
mapという変数があることに留意
*/

(function(){
  // 位置情報をもつ変数を用意
  let pos = new google.maps.LatLng(
   <%= @latlng[0] %>, //latitude
   <%= @latlng[1] %>  //longitude
  );

  mapInstance.setCenter(pos)
  let marker = new google.maps.Marker({
    map: mapInstance,
    position: pos
  });
})()

app/views/subscriptions/new.html.erb
<% provide(:title, "サブスク審査申し込み") %>

<h1>加盟店サブスクショップ審査</h1>

<%= form_with(model: @subscription, url: subscription_confirm_path(@subscription, owner_id: current_owner.id), method: :post, local: true) do |form| %>
  <%= render 'shared/error_messages' , object: @subscription %>

  <div class="field">
    <%= form.label :お店の名前 %> <span class="must">必須</span><br/>
    <%= form.text_field :name, :required => true, id: :subscription_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :サイトURL %> <span class="must">必須</span><br/>
    <%= form.text_field :site, :required => true, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "加盟店登録の審査申請" %>
  </div>
<% end %>
<%= link_to 'トップ', root_path %> |

<%= link_to '一覧へ', owner_subscriptions_path(current_owner) %>

app/views/subscriptions/setup.html.erb
<%
=begin%>
 <% provide(:title, "サブスクページ") %>
<div class="togethere-background"></div>
    <div class="sr-root">
      <div class="sr-main">
        <header class="sr-header">
          <div class="sr-header__logo"></div>
        </header>
        <h1>巡グルメプランを選択して下さい</h1>

        <div class="price-table-container">

          <section>
            <img
              src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPf1fl_6GCRJUByMI9OSkIz02ssTC23yXJTQ&usqp=CAU"
              width="120"
              height="120"
            />
            <div class="name">巡グルメ1（仮）</div>
            <div class="price">￥1980</div>
            <div class="duration">/月</div>
            <button id="checkout-button">選択</button>
            <% # link_to '選択', owner_shop_subscription_path(plan: "price_1HpOFzLKoWxnLyg76fWVCydG", plan_id: Rails.application.secrets.price_1HpOFzLKoWxnLyg76fWVCydG), class: 'btn btn-xs btn-primary', remote: true %>


          </section>&nbsp;

          <section>
            <img
              src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPf1fl_6GCRJUByMI9OSkIz02ssTC23yXJTQ&usqp=CAU"
              width="120"
              height="120"
            />
            <div class="name">巡グルメ2（仮）</div>
            <div class="price">￥4980</div>
            <div class="duration">/月</div>
            <button id="checkout-button-2">選択</button>
          </section>&nbsp;

          <section>
            <img
              src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPf1fl_6GCRJUByMI9OSkIz02ssTC23yXJTQ&usqp=CAU"
              width="120"
              height="120"
            />
            <div class="name">巡グルメ3（仮）</div>
            <div class="price">￥19800</div>
            <div class="duration">/月</div>
            <button id="checkout-button-3">選択</button>
          </section>

        </div>
        <div id="error-message"></div>
      </div>
    </div>

<script src="https://js.stripe.com/v3/"></script>
<script>
  var stripe = Stripe('pk_test_51HI2E1LKoWxnLyg7OJ1ZS1lqEwJBInfzh1jNpz8Kr6FHN7AQS2bI9WE9FGeF0SoftlZJM0CI6xYF6eRLm86LgLrp00h2NQLnuG');
  var checkoutButton = document.getElementById('checkout-button');

  checkoutButton.addEventListener('click', function() {
    stripe.redirectToCheckout({
      sessionId: '<%= @plan1.id %>'
    }).then(function (result) {
    });
  });
</script>

<script>
  var stripe = Stripe('pk_test_51HI2E1LKoWxnLyg7OJ1ZS1lqEwJBInfzh1jNpz8Kr6FHN7AQS2bI9WE9FGeF0SoftlZJM0CI6xYF6eRLm86LgLrp00h2NQLnuG');
  var checkoutButton = document.getElementById('checkout-button-2');

  checkoutButton.addEventListener('click', function() {
    stripe.redirectToCheckout({
      sessionId: '<%= @plan2.id %>'
    }).then(function (result) {
    });
  });
</script>

<script>
  var stripe = Stripe('pk_test_51HI2E1LKoWxnLyg7OJ1ZS1lqEwJBInfzh1jNpz8Kr6FHN7AQS2bI9WE9FGeF0SoftlZJM0CI6xYF6eRLm86LgLrp00h2NQLnuG');
  var checkoutButton = document.getElementById('checkout-button-3');

  checkoutButton.addEventListener('click', function() {
    stripe.redirectToCheckout({
      sessionId: '<%= @plan3.id %>'
    }).then(function (result) {
    });
  });
</script> 
<%
=end%>

app/views/subscriptions/site.html.erb
<% provide(:title, "本サイトについて") %>

app/views/subscriptions/subscription_all_shop.html.erb
<% provide(:title, "加盟店舗全て") %>

<h1>加盟店舗のお店一覧</h1>

<hr class="my-3">


<% @subscriptions.each do |subscription| %>
  <div class="container mt-5">
    <section class="dark-grey-text">
      <div class="row align-items-center">
        <div class="col-lg-5 col-xl-3">
          <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
            <% if subscription.image_subscription.present? %>
              <%= image_tag subscription.image_subscription_url, width: '100%' %>
            <% else %>
              <p></p>
            <% end %>
          </div>
        </div>
        <div class="col-lg-7 col-xl-8">
          <span class="badge badge-success">加盟店</span>
          <% if subscription.trial == true %>
            <span class="badge badge-warning">トライアルでも利用可能</span>
          <% elsif subscription.trial == false %>
            <span class="badge badge-warning">トライアルチケットでは利用できません。</span>
          <% end %>
          <h4 class="font-weight-bold mb-3"><strong><%= subscription.name %></strong></h4>
          <p class="dark-grey-text"><%= subscription.title %></p>
          <%= link_to "詳細", owner_subscription_path(subscription.id, owner_id: subscription.owner_id), class: 'btn btn-outline-primary btn-rounded text-primary' %>
        </div>
      </div>
      <hr class="my-3">
    </section>
  </div>
<% end%>

<br>
<%= link_to 'カテゴリー一覧へ', categories_path %>