config/routes.rb
Rails.application.routes.draw do

  get 'ticket_logs' => "ticket_logs#index", as: :ticket_logs#チケット使用履歴
  delete "ticket_logs", to: "ticket_logs#destroy", as: 'logs_destroy'
  get 'ticket' => "tickets#user_have_ticket", as: :user_have_ticket#チケット使用履歴

  root 'static_pages#top'#トップページ
  get 'paypaytest' => "static_pages#paypaytest"#paypaytest
  get 'top_owner' => "static_pages#top_owner"#経営者様トップページ
  get 'top_user' => "static_pages#top_user"#利用者様トップページ
  get 'megurume_line' => "static_pages#megurume_line"#LINE誘導
  get 'discussion' => "static_pages#discussion"#相談窓口
  get 'specified_commercial_transaction_law' => "static_pages#specified_commercial_transaction_law"#特定商取引法
  get 'how_to_use' => "subscriptions#how_to_use", as: :how_to_use#ご利用方法について
  get 'plan_description' => "subscriptions#plan_description", as: :plan_description#プラン説明
  get 'kiyaku' => "subscriptions#kiyaku", as: :kiyaku#利用規約
  get 'privacy_policy' => "subscriptions#privacy_policy", as: :privacy_policy#プライバシーポリシー
  get 'site' => "subscriptions#site", as: :site#サイトについて
  get 'company_profile' => "subscriptions#company_profile", as: :company_profile#会社概要

  get 'subscriptions/setup', to: 'subscriptions#setup', as: :setup_subscriptions#経営者のプラン内容
  get '/cancel', to: 'user_plans#cancel'
  get '/success', to: 'user_plans#success'
  get '/private_store_cancel', to: 'private_store_user_plans#cancel'
  get '/private_store_success', to: 'private_store_user_plans#success'

  get 'categories/shop_list', to: 'categories#shop_list', as: :shop_list_categories
  get 'categories/recommend', to: 'categories#recommend', as: :recommend_categories#おすすめショップ

  get 'subscriptions/show_sample', to: 'subscriptions#show_sample', as: :show_sample_subscriptions
  get 'subscriptions/shop_case', to: 'subscriptions#shop_case', as: :shop_case#ショップ事例

  get 'subscriptions/:id/ticket', to: 'users#ticket', as: :use_ticket #チケット発行ページ
  get 'private_store/:id/ticket', to: 'private_store_users#ticket', as: :private_store_use_ticket #private_store用チケット発行ページ
  get 'private_store/:id/new_ticket', to: 'private_store_user_plans#new', as: :private_store_new_ticket #private_store用サブスクを始める
  get 'subscription/:id/new_ticket', to: 'user_plans#new', as: :subscription_new_ticket #subscription用サブスクを始める

  get '/subscriptions/:subscription_id/subscription_reviews', to: 'reviews#subscription_reviews', as: :subscription_reviews #サブスクレビューページ
  get '/private_stores/:private_store_id/private_store_reviews', to: 'reviews#private_store_reviews', as: :private_store_reviews #個人店舗レビューページ
  get '/subscriptions/:subscription_id/edit_subscription_reviews/:id', to: 'reviews#edit_subscription_reviews', as: :edit_subscription_reviews #サブスクレビューページ

  get '/ticket_success', to: 'tickets#ticket_success', as: :ticket_success
  patch 'users/:user_id/tickets/:id/ticket_update_after_second_time', to: 'tickets#ticket_update_after_second_time', as: :ticket_update_after_second_time
  patch 'users/:user_id/tickets/:id/edit_user_ticket', to: 'tickets#edit_user_ticket', as: :edit_user_ticket

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, path: 'users', controllers: {
   # omniauth_callbacks:  'users/omniauth_callbacks',
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/sign_up/confirm', to: 'users/registrations#confirm'
    patch 'users/sign_up/complete', to: 'users/registrations#complete'
    post 'users/sign_up/complete', to: 'users/registrations#complete'
    get "/devise/auth/facebook/callback" => "users/omniauth_callbacks#facebook"
    get "/devise/auth/twitter/callback" => "users/omniauth_callbacks#twitter"
    match "/users/auth/line" => "users/omniauth_callbacks#passthru", via: [:get, :post]
    match "/users/auth/line/callback" => "users/omniauth_callbacks#line", via: [:get, :post]
    get 'users/sign_up', to: 'users#new'
  end

  devise_for :owners, path: 'owners', controllers: {
    sessions:      'owners/sessions',
    passwords:     'owners/passwords',
    registrations: 'owners/registrations'
  }
  devise_scope :owner do
    get "/devise/auth/facebook_owner/callback" => "owners/omniauth_callbacks#facebook_owner"
    get "/devise/auth/twitter_owner/callback" => "owners/omniauth_callbacks#twitter_owner"
    match "/owners/auth/line" => "owners/omniauth_callbacks#passthru", via: [:get, :post]
    match "/owners/auth/line/callback" => "owners/omniauth_callbacks#line_owner", via: [:get, :post]
  end

  devise_scope :owner do
    post 'owners/sign_up/confirm', to: 'owners/registrations#confirm'
    patch 'owners/sign_up/complete', to: 'owners/registrations#complete'
    post 'owners/sign_up/complete', to: 'owners/registrations#complete'
  end

  resource :admin, except: %i(new create destroy) do
    get 'account', on: :collection #アカウントページ
    member do
      get 'private_owner_edit'
      patch 'private_owner_update'
      get 'subscription_owner_edit'
      patch 'subscription_owner_update'
      # patch 'private_stores/:private_stores_id/private_owner_update', to: 'admins#private_owner_update', as: :private_owner_update
      get 'owner_edit' #個人情報編集
      patch 'owner_update' #個人情報編集
      get 'user_edit' #
      patch 'user_update' #
    end
  end
  resources :blogs#管理者が書くサブスクnews
  get 'reviews/list' => "reviews#list"#利用者ではない人用の表示ページ
  get 'subscriptions/list' => "subscriptions#list"#まだ決まってない。使わないかもしれない
  get 'blogs/index'#まだ決まってない。使わないかもしれない

  get 'suports', to: "suports#index"#サポート画面
  post 'suports/confirm' => "suports#confirm"#サポート確認画面
  post 'suports/thanks' => "suports#thanks"#サポート完了通知仮面

  get 'contacts', to: "contacts#index"#お問い合わせ画面
  post 'contacts/confirm' => "contacts#confirm"#お問い合わせ確認画面
  post 'contacts/thanks' => "contacts#thanks"#お問い合わせ完了通知仮面

  resources :medias#メディア
  resources :interviews#経営者様インタビュー
  resources :cupons#クーポン
  resources :products#QRコード

  get 'owners/deleted_owners'#論理削除された経営者
  resources :owners do
    get :search, on: :collection #オーナーの名前であいまい検索 追加分
    get :subscription_private_store_select, on: :member #加盟店か個人店かの選択
    get :subscription_private_store_judging_select, on: :member #加盟店か個人店かの選択と審査の選択
    member do
      post "thanks" #会員登録完了通知画面
      get 'owner_account' #アカウントページ
      patch 'update_deleted_owners' #アカウントページ論理削除
    end
    resources :subscriptions do
      get 'like_lunch', on: :member
      member do
        get 'edit_recommend' #おすすめ追加よう
        patch 'update_recommend' #おすすめ店舗に加えるたり外すよう
        get '/owner_subscriptions', to: "subscriptions#owner_subscriptions", as: :owner_subscriptions
        post :takeout
      end
    end
    resources :private_stores do
      resources :images
      member do
        get 'edit_recommend' #おすすめ追加よう
        patch 'update_recommend' #おすすめ店舗に加えるたり外すよう
        #get "confirm", to: "private_store_user_plans#confirm"
        #get "update_confirm", to: "private_store_user_plans#update_confirm"
        #get 'plans_new', to: "private_store_user_plans#new", as: 'plans_new' #利用者のプラン内容
        #get "plans_edit", to: "private_store_user_plans#edit", as: 'plans_edit'
              #patch "plans_update", to: "private_store_user_plans#update", as: 'plans_update'
        #delete "plans_destroy", to: "private_store_user_plans#destroy", as: 'plans_destroy'
        get '/owner_private_stores', to: "private_stores#owner_private_stores", as: :owner_private_stores
        post :takeout
      end
    end
  end
  resources :maps
  resources :categories, only: %i(index) do
    get 'like_lunch', on: :member
    post 'search', on: :collection
  end
  get 'categories/trial_shop', to: 'categories#trial_shop', as: :trial_shop#トライアルのお店一覧
  get 'private_stores/private_all_shop', to: 'private_stores#private_all_shop', as: :private_all_shop#個人店舗のお店一覧
  get 'subscriptions/subscription_all_shop', to: 'subscriptions#subscription_all_shop', as: :subscription_all_shop#加盟店舗のお店一覧
  post 'subscriptions/subscription_confirm', to: 'subscriptions#subscription_confirm', as: :subscription_confirm#加盟店舗の審査の確認画面
  patch 'subscriptions/subscription_judging', to: 'subscriptions#subscription_judging'#加盟店舗の審査
  post 'subscriptions/subscription_judging', to: 'subscriptions#subscription_judging'#加盟店舗の審査

  post 'private_stores/private_store_confirm', to: 'private_stores#private_store_confirm', as: :private_store_confirm#個人店舗の審査の確認画面
  patch 'private_stores/private_store_judging', to: 'private_stores#private_store_judging'#個人店舗の審査
  post 'private_stores/private_store_judging', to: 'private_stores#private_store_judging'#個人店舗の審査

  get 'users/user_subscription_email', to: 'users#user_subscription_email' #加盟店の利用者から経営者へメール
  patch 'users/user_subscription_confirm', to: 'users#user_subscription_confirm'
  patch 'users/user_subscription_thanks', to: 'users#user_subscription_thanks'
  post 'users/user_subscription_thanks', to: 'users#user_subscription_thanks'

  get 'users/user_private_store_email', to: 'users#user_private_store_email' #加盟店の利用者から経営者へメール
  patch 'users/user_private_store_confirm', to: 'users#user_private_store_confirm'
  patch 'users/user_private_store_thanks', to: 'users#user_private_store_thanks'
  post 'users/user_private_store_thanks', to: 'users#user_private_store_thanks'

  get 'users/deleted_users'##論理削除された利用者
  resources :users do
    collection do
      get :search # ユーザーの名前であいまい検索 追加分
      # get "sms_auth", to: "sms#new"
      # post "sms_auth", to: "sms#confirm"
    end
    get :search, on: :collection # ユーザーの名前であいまい検索 追加分
    # get 'subscriptions/:id/edit_favorite', to: "subscriptions#edit_favorite", as: :edit_favorite#お気に入り店舗に加えるたり外すよう
    # patch 'subscriptions/:id/update_recommend', to: "subscriptions#update_favorite", as: :update_favorite #お気に入り店舗に加えるたり外すよう
    # get 'subscriptions/favorite', to: 'subscriptions#favorite', as: :favorite_subscriptions#おすすめショップ
    resources :tickets#サブスクチケット

app/models/category.rb
class Category < ApplicationRecord
  has_many :subscriptions
  has_many :private_stores

  # has_many :category_subscriptions
  # has_many :subscriptions, through: :category_subscriptions
  #has_many :category_private_stores
  #has_many :private_stores, through: :category_private_stores
  # mount_uploader :image_category, CategoryUploader

  def self.search(search) #ここでのself.はCategory.を意味する
    if search
      where(['name LIKE ?', "%#{search}%"])#検索とnameの部分一致を表示。Category.は省略
    else
      all #全て表示。Category.は省略
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:like_lunch]
  # before_action :set_subscription, only: [:show]
  before_action :categories_lock, only: %i(new edit)
  before_action :current_user_email_present?, only: %i(trial_shop)


  def index
    @category_all = Category.all
  end

  def like_lunch
    @subscriptions = @category.subscriptions.where(admin_subscription_check: "承認")
    @private_stores = @category.private_stores.where(admin_private_check: "承認")
    @subscriptions = @category.subscriptions
    @private_stores = @category.private_stores
    if current_user.present?
      current_user.update!(select_trial: false)  if current_user.plan_canceled || (!current_user.trial_stripe_success && current_user.select_trial)
    end
  end

  def trial_shop
    @subscriptions = Subscription.where(trial: true)
    @private_stores = PrivateStore.where(trial: true)
    if current_user.present?
      current_user.update!(select_trial: true) if current_user.price.blank?
    end
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    if params[:category_id].present?
      redirect_to like_lunch_category_url(params[:category_id])
    else
      redirect_to categories_url
    end
  end


  def shop_list
    @subscriptions = Subscription.where(recommend: true).order(created_at: :asc).paginate(page: params[:page], per_page: 10)
    @private_stores = PrivateStore.all.order(created_at: :asc).paginate(page: params[:page], per_page: 10)
  end

  def recommend
    @subscriptions = Subscription.where(recommend: true).order(created_at: :asc).paginate(page: params[:page], per_page: 10)
    @private_stores = PrivateStore.where(recommend: true).where(admin_private_check: "個人店舗データ反映済み").order(created_at: :asc).paginate(page: params[:page], per_page: 10)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    def set_subscription
      @subscription = Subscription.find(params[:id])
    end


    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :image_category, :user_id, :owner_id)
    end

    def categories_lock
      unless current_admin.present?
        redirect_to root_url, notice: '権限がありません'
      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def categories_list(categories)
    categories_list= []
    categories.each do |category|
      categories_list.push([category.name, category.id])
    end
    return categories_list
  end
end

app/views/categories/_show.html.erb
<% provide(:title, "サブスクページ作成") %>

<h1>shop list</h1>

<% @subscriptions.each do |subscription| %>
<div class="container mt-5">
  <section class="dark-grey-text">
    <div class="row align-items-center">
      <div class="col-lg-5 col-xl-3">
        <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
          <% if subscription.image_subscription.present? %>
            <%= image_tag subscription.image_subscription_url, width: '100%', height: "300" %>
          <% else %>
            <p>なし</p>
          <% end %>
        </div>
      </div>
      <div class="col-lg-7 col-xl-8">
        <span class="badge badge-success">加盟店</span>
        <h4 class="font-weight-bold mb-3"><strong><%= subscription.name %></strong></h4>

        <p class="dark-grey-text"><%= subscription.title %></p>

        <%= link_to "詳細", owner_subscription_path(id: subscription.id, owner_id: subscription.owner_id, shop_id: subscription.shop_id), class: 'btn btn-outline-primary btn-rounded text-primary' %>

      </div>
    </div>
    <hr class="my-3">
  </section>
</div>
<% end%>

<% @private_stores.each do |private_store| %>
<div class="container mt-5">
  <section class="dark-grey-text">
    <div class="row align-items-center">
      <div class="col-lg-5 col-xl-3">
        <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
          <% if private_store.image_private_store.present? %>
            <%= image_tag private_store.image_private_store_url, width: '100%', height: "300" %>
          <% else %>
            <p>なし</p>
          <% end %>
        </div>
      </div>
      <div class="col-lg-7 col-xl-8">
        <span class="badge badge-primary">個人店舗</span>
        <h4 class="font-weight-bold mb-3"><strong><%= private_store.name %></strong></h4>

        <p class="dark-grey-text"><%= private_store.title %></p>

        <%= link_to "詳細", owner_private_store_path(id: private_store.id, owner_id: private_store.owner_id, shop_id: private_store.shop_id), class: 'btn btn-outline-primary btn-rounded text-primary' %>

      </div>
    </div>
    <hr class="my-3">
  </section>
</div>
<% end%>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>カテゴリからお店を探そう！</h1>

<div class="recommend-shop">
  <%= link_to shop_list_categories_path, class: "btn-gradient-radius-orange" do%>
  全てのお店のリストはこちら&nbsp;<i class="fas fa-chevron-circle-right"></i>
  <% end %>
</div>

<div class="search">
  <%= render partial: "categories/select", locals: {categories: @category_all} %>
</div>
<div class="category-list">
  <% @category_all.each do |category| %><%# カテゴリーを全てeach %>
    <div class="category-item">
      <%= link_to image_tag(category.image_category, :size => '280x200'), like_lunch_category_path(category), class: "image-menu" %>
      <div class="category-shop-btn">
        <%= link_to "#{category.name}", like_lunch_category_path(category) %>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/like_lunch.html.erb
<% provide(:title, "カテゴリー") %>

<h1><%= @category.name %></h1>

<hr class="my-3">

<% @subscriptions.each do |subscription| %>
  <div class="container mt-5">
    <section class="dark-grey-text">
      <div class="row align-items-center">
        <div class="col-lg-5 col-xl-3">
          <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
            <% if subscription.image_subscription.present? %>
              <%= image_tag subscription.image_subscription_url, width: '100%' %>
            <% else %>
              <p></p>
            <% end %>
          </div>
        </div>
        <div class="col-lg-7 col-xl-8">
        <span class="badge badge-success">加盟店</span>
          <% if subscription.trial == true %>
            <span class="badge badge-warning">トライアルでも利用可能</span>
          <% elsif subscription.trial == false %>
            <span class="badge badge-warning">トライアルチケットでは利用できません。</span>
          <% end %>
          <h4 class="font-weight-bold mb-3"><strong><%= subscription.name %></strong></h4>
          <p class="dark-grey-text"><%= subscription.title %></p>
          <%= link_to "詳細", owner_subscription_path(subscription.id, owner_id: subscription.owner_id), class: 'btn btn-outline-primary btn-rounded text-primary' %>
        </div>
      </div>
      <hr class="my-3">
    </section>
  </div>
<% end%>

<% @private_stores.each do |private_store| %>
  <div class="container mt-5">
    <section class="dark-grey-text">
      <div class="row align-items-center">
        <div class="col-lg-5 col-xl-3">
          <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
            <% if private_store.image_private_store.present? %>
              <%= image_tag private_store.image_private_store_url, width: '100%' %>
            <% else %>
              <p></p>
            <% end %>
          </div>
        </div>
        <div class="col-lg-7 col-xl-8">
        <span class="badge badge-primary">個人店舗</span>
          <% if private_store.trial == true %>
            <span class="badge badge-warning">トライアルでも利用可能</span>
          <% elsif private_store.trial == false %>
            <span class="badge badge-warning">トライアルチケットでは利用できません。</span>
          <% end %>
          <h4 class="font-weight-bold mb-3"><strong><%= private_store.name %></strong></h4>
          <p class="dark-grey-text"><%= private_store.title %></p>
          <%= link_to "詳細", owner_private_store_path(private_store.id, owner_id: private_store.owner_id), class: 'btn btn-outline-primary btn-rounded text-primary' %>
        </div>
      </div>
      <hr class="my-3">
    </section>
  </div>
<% end%>

<br>
<%= link_to 'カテゴリー一覧へ', categories_path %>

app/views/categories/other.html.erb
<%= render partial: 'categories/show/' %>

app/views/categories/recommend.html.erb
<% provide(:title, "おすすめ店舗") %>
<p id="notice"><%= notice %></p>

<h1>オススメ店舗</h1>


<% @subscriptions.each do |subscription| %>
  <div class="container mt-5">
    <section class="dark-grey-text">
      <div class="row align-items-center">
        <div class="col-lg-5 col-xl-3">
          <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
            <% if subscription.image_subscription.present? %>
              <%= image_tag subscription.image_subscription_url, width: '100%' %>
            <% else %>
              <p></p>
            <% end %>
          </div>
        </div>
        <div class="col-lg-7 col-xl-8">
        <span class="badge badge-success">加盟店</span>
          <h4 class="font-weight-bold mb-3"><strong><%= subscription.name %></strong></h4>
          <p class="dark-grey-text"><%= subscription.title %></p>
          <%= link_to "詳細", owner_subscription_path(id: subscription.id, owner_id: subscription.owner_id), class: 'btn btn-outline-primary btn-rounded text-primary' %>
        </div>
      </div>
      <hr class="my-3">
    </section>
  </div>
<% end%>

<% @private_stores.each do |private_store| %>
<div class="container mt-5">
  <section class="dark-grey-text">
    <div class="row align-items-center">
      <div class="col-lg-5 col-xl-3">
        <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
          <% if private_store.image_private_store.present? %>
            <%= image_tag private_store.image_private_store_url, width: '100%' %>
          <% else %>
            <p></p>
          <% end %>
        </div>
      </div>
      <div class="col-lg-7 col-xl-8">
      <span class="badge badge-primary">個人店舗</span>
        <h4 class="font-weight-bold mb-3"><strong><%= private_store.name %></strong></h4>
        <p class="dark-grey-text"><%= private_store.title %></p>
        <%= link_to "詳細", owner_private_store_path(id: private_store.id, owner_id: private_store.owner_id), class: 'btn btn-outline-primary btn-rounded text-primary' %>
      </div>
    </div>
    <hr class="my-3">
  </section>
</div>
<% end%>
<%= will_paginate(@subscriptions, class: "pagination justify-content-center mt-6 mb-7", renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

app/views/categories/shop_list.html.erb
<% provide(:title, "ショップリスト") %>
<h1>ショップリスト</h1>

<% @subscriptions.each do |subscription| %>
  <div class="container mt-5">
    <section class="dark-grey-text">
      <div class="row align-items-center">
        <div class="col-lg-5 col-xl-3">
          <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
            <% if subscription.image_subscription.present? %>
              <%= image_tag subscription.image_subscription_url ,width: '100%' %>
            <% else %>
              <p></p>
            <% end %>
          </div>
        </div>
        <div class="col-lg-7 col-xl-8">
        <span class="badge badge-success">加盟店</span>
          <% if subscription.trial == true %>
            <span class="badge badge-warning">トライアルでも利用可能</span>
          <% elsif subscription.trial == false %>
            <span class="badge badge-warning">トライアルチケットでは利用できません。</span>
          <% end %>
          <h4 class="font-weight-bold mb-3"><strong><%= subscription.name %></strong></h4>
          <p class="dark-grey-text"><%= subscription.title %></p>
          <%= link_to "詳細", owner_subscription_path(id: subscription.id, owner_id: subscription.owner_id), class: 'btn btn-outline-primary btn-rounded text-primary' %>
        </div>
      </div>
      <hr class="my-3">
    </section>
  </div>
<% end%>
<% @private_stores.each do |private_store| %>
  <div class="container mt-5">
    <section class="dark-grey-text">
      <div class="row align-items-center">
        <div class="col-lg-5 col-xl-3">
          <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
            <% if private_store.image_private_store.present? %>
              <%= image_tag private_store.image_private_store_url, width: '100%' %>
            <% else %>
              <p></p>
            <% end %>
          </div>
        </div>
        <div class="col-lg-7 col-xl-8">
        <span class="badge badge-primary">個人店舗</span>
          <% if private_store.trial == true %>
            <span class="badge badge-warning">トライアルでも利用可能</span>
          <% elsif private_store.trial == false %>
            <span class="badge badge-warning">トライアルチケットでは利用できません。</span>
          <% end %>
          <h4 class="font-weight-bold mb-3"><strong><%= private_store.name %></strong></h4>
          <p class="dark-grey-text"><%= private_store.title %></p>
          <%= link_to "詳細", owner_private_store_path(id: private_store.id, owner_id: private_store.owner_id), class: 'btn btn-outline-primary btn-rounded text-primary' %>
        </div>
      </div>
      <hr class="my-3">
    </section>
  </div>
  <% end%>
<%= will_paginate(@subscriptions, class: "pagination justify-content-center mt-6 mb-7", renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

app/views/categories/trial_shop.html.erb
<% provide(:title, "トライアルショップ") %>

<h1>トライアルでも利用できる店舗</h1>

<hr class="my-3">

<% @subscriptions.each do |subscription| %>
  <div class="container mt-5">
    <section class="dark-grey-text">
      <div class="row align-items-center">
        <div class="col-lg-5 col-xl-3">
          <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
            <% if subscription.image_subscription.present? %>
              <%= image_tag subscription.image_subscription_url, width: '100%' %>
            <% else %>
              <p></p>
            <% end %>
          </div>
        </div>
        <div class="col-lg-7 col-xl-8">
          <span class="badge badge-success">加盟店</span>
          <span class="badge badge-warning">トライアルでも利用可能</span>
          <h4 class="font-weight-bold mb-3"><strong><%= subscription.name %></strong></h4>
          <p class="dark-grey-text"><%= subscription.title %></p>
          <%= link_to "詳細", owner_subscription_path(subscription.id, owner_id: subscription.owner_id), class: 'btn btn-outline-primary btn-rounded text-primary' %>
        </div>
      </div>
      <hr class="my-3">
    </section>
  </div>
<% end%>

<% @private_stores.each do |private_store| %>
  <div class="container mt-5">
    <section class="dark-grey-text">
      <div class="row align-items-center">
        <div class="col-lg-5 col-xl-3">
          <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
            <% if private_store.image_private_store.present? %>
              <%= image_tag private_store.image_private_store_url, width: '100%' %>
            <% else %>
              <p></p>
            <% end %>
          </div>
        </div>
        <div class="col-lg-7 col-xl-8">
          <span class="badge badge-primary">個人店舗</span>
          <span class="badge badge-warning">トライアルでも利用可能</span>
          <h4 class="font-weight-bold mb-3"><strong><%= private_store.name %></strong></h4>
          <p class="dark-grey-text"><%= private_store.title %></p>
          <%= link_to "詳細", owner_private_store_path(private_store.id, owner_id: private_store.owner_id), class: 'btn btn-outline-primary btn-rounded text-primary' %>
        </div>
      </div>
      <hr class="my-3">
    </section>
  </div>
<% end%>

<br>
<%= link_to 'トップへ', root_path %>